load("//hack:typescript.bzl", "app")

package(default_visibility = ["//visibility:public"])

app(
    name = "bazel-remote-cache",
    label = "//apps/bazel-remote-cache",
    deps = [
        "@npm//@types/lodash-es",
        "@npm//lodash-es",
    ],
)
